-- Tabele główne
CREATE TABLE global_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hourly_price_limit DECIMAL(10, 2) NOT NULL,
    message TEXT NULL,
    PRIMARY KEY (id)
);

-- Statuses
CREATE TABLE statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT statuses_status_unique UNIQUE (status)
);

-- Roles
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT roles_name_unique UNIQUE (name)
);

-- Subjects
CREATE TABLE subjects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    status_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (status_id) REFERENCES statuses(id)
);

-- Users
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id INTEGER NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    account_status_id INTEGER NOT NULL,
    address TEXT NULL,
    phone_number VARCHAR(20) NULL,
    fcm_token VARCHAR(255) NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (account_status_id) REFERENCES statuses(id)
);

CREATE TABLE refresh_tokens (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(512) NOT NULL,
    user_id    INTEGER NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_token_unique UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_fcm_tokens (
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fcm_token  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fcm_token UNIQUE (fcm_token)
);

-- Availability_slots
CREATE TABLE availability_slots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME(0) WITHOUT TIME ZONE NOT NULL,
    end_time TIME(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

-- Offers
CREATE TABLE offers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tutor_id INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    details TEXT NULL,
    subject_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    global_limit_id INTEGER NOT NULL,
    offer_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (tutor_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (status_id) REFERENCES statuses(id),
    FOREIGN KEY (global_limit_id) REFERENCES global_limits(id)
);

-- Offer_slots
CREATE TABLE offer_slots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    offer_id INTEGER NOT NULL,
    availability_slot_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT offer_slots_unique UNIQUE (offer_id, availability_slot_id),
    FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE,
    FOREIGN KEY (availability_slot_id) REFERENCES availability_slots(id)
);

-- Bookings
CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    availability_slot_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    offer_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    booking_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (availability_slot_id) REFERENCES availability_slots(id),
    FOREIGN KEY (status_id) REFERENCES statuses(id),
    FOREIGN KEY (offer_id) REFERENCES offers(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
);

-- Reviews (z created_at i updated_at)
CREATE TABLE reviews (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating     SMALLINT NOT NULL,
    tutor_id   INTEGER NOT NULL,
    comment    TEXT NULL,
    booking_id INTEGER NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (tutor_id) REFERENCES users(id),
    FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

-- Chats
CREATE TABLE chats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    blocked_by INTEGER NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (blocked_by) REFERENCES users(id)
);

-- Messages
CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (chat_id) REFERENCES chats(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Chat_participants
CREATE TABLE chat_participants (
    chat_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    FOREIGN KEY (chat_id) REFERENCES chats(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Indeksy
CREATE INDEX idx_chat_participants_chat_id ON chat_participants(chat_id);
CREATE INDEX idx_chat_participants_user_id ON chat_participants(user_id);
CREATE INDEX idx_messages_chat_id ON messages(chat_id);
CREATE INDEX idx_messages_user_id ON messages(user_id);
CREATE INDEX idx_bookings_offer_id ON bookings(offer_id);
CREATE INDEX idx_bookings_student_id ON bookings(student_id);
CREATE INDEX idx_offers_tutor_id ON offers(tutor_id);
CREATE INDEX idx_offers_subject_id ON offers(subject_id);
CREATE INDEX idx_offers_status_id ON offers(status_id);
CREATE INDEX idx_reviews_tutor_id ON reviews(tutor_id);
CREATE INDEX idx_reviews_booking_id ON reviews(booking_id);
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_fcm_tokens_user ON user_fcm_tokens(user_id);
CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_offers_created_at ON offers(created_at);
CREATE INDEX idx_offer_slots_offer_id ON offer_slots(offer_id);