# Database connection settings
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/EduLink_Database
spring.datasource.username=postgres
spring.datasource.password=student

# JPA configuration ? disable schema validation during development
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true