# Database connection settings
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA configuration ? disable schema validation during development
spring.jpa.hibernate.ddl-auto=validate
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
    # Development
spring.jpa.show-sql=true

    # Production
    #spring.jpa.show-sql=false

# application.properties
logging.level.com.google.firebase=DEBUG
logging.level.com.vectorpeaks.backend=DEBUG

    # Production
    #logging.level.com.google.firebase=INFO
    #logging.level.com.vectorpeaks.backend=INFO

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

# JWT token blacklist configuration (time to refresh - clean up rate)
jwt.blacklist-cleanup-rate=${JWT_BLACKLIST_CLEANUP_RATE}

# ===== Disable Spring Boot default user configuration =====
spring.security.user.name=testuser
spring.security.user.password=testpass

# ===== CORS (development rn) =====
cors.allowed-origins=http://localhost:3000,http://localhost:8081,http://10.0.2.2:8080

    # production
    # ===== CORS =====
    #cors.allowed-origins=https://your-frontend-domain.com